// lib/data.ts
import { Product, Category } from '@/types'

export const products: Product[] = [
  {
    id: '1',
    name: 'Кровавый ангел – Капитан Терминатор',
    slug: 'blood-angel-captain',
    price: 499,
    oldPrice: 799,
    image: '/images/ba-captain.jpg',
    images: ['/images/ba-captain.jpg', '/images/ba-captain-2.jpg'],
    category: 'Космодесант',
    categorySlug: 'space-marines',
    subcategory: 'Герои',
    description: 'Монументальная модель капитана ордена Кровавых Ангелов в терминаторской броне. Идеально для Warhammer 40k.',
    shortDesc: 'Герой для армии Империума',
    fileFormat: 'STL, OBJ',
    scale: '32mm',
    type: 'infantry',
    faction: 'Кровавые Ангелы',
    gameSystem: 'Warhammer 40k',
    tags: ['герой', 'терминатор', 'космодесант', 'империум'],
    inStock: true,
    downloadsCount: 1240,
    isDigital: true,
    popularity: 98,
    dateAdded: '2025-01-10',
    featured: true,
    new: false,
  },
  {
    id: '2',
    name: 'Проклятый легионер – Чумной рыцарь',
    slug: 'plague-knight',
    price: 599,
    image: '/images/plague-knight.jpg',
    images: ['/images/plague-knight.jpg'],
    category: 'Легионы Хаоса',
    categorySlug: 'chaos',
    subcategory: 'Пехота',
    description: 'Смертоносный воин Нургла, покрытый гниющими доспехами. Поддержка для Chaos Space Marines.',
    shortDesc: 'Служитель чумы',
    fileFormat: 'STL, ZIP',
    scale: '28mm',
    type: 'infantry',
    faction: 'Смертный гвардеец',
    gameSystem: 'Warhammer 40k',
    tags: ['хаос', 'нургл', 'пехота'],
    inStock: true,
    downloadsCount: 870,
    isDigital: true,
    popularity: 85,
    dateAdded: '2025-01-15',
    featured: false,
    new: false,
  },
  {
    id: '3',
    name: 'Йомены Новой Антиохии',
    slug: 'trench-spec-ops',
    price: 349,
     image: '/images/3/1.png',             // первое фото для каталога
  images: [
    '/images/3/1.png',
    '/images/3/2.png',
    '/images/3/3.png',
    '/images/3/4.png',
    '/images/3/5.png',
    '/images/3/6.png',
    '/images/3/7.png',
    '/images/3/8.png',
    '/images/3/9.png',
    '/images/3/10.png',
    '/images/3/11.png',
    '/images/3/12.png',
    '/images/3/13.png',
  ],
    category: 'Trench Crusade',
    categorySlug: 'trench-crusade',
    subcategory: 'Отряды',
    description: 'Отряд закалённых в траншеях бойцов с противогазами и автоматическим оружием. Для Trench Crusade.',
    shortDesc: 'Элита траншей',
    fileFormat: 'STL, OBJ',
    scale: '32mm',
    type: 'infantry',
    faction: 'Антанта',
    gameSystem: 'Trench Crusade',
    tags: ['траншея', 'пехота', 'спецназ'],
    inStock: true,
    downloadsCount: 2100,
    isDigital: true,
    popularity: 96,
    dateAdded: '2025-02-01',
    featured: true,
    new: true,
  },
  {
    id: '4',
    name: 'Древний красный дракон',
    slug: 'ancient-red-dragon',
    price: 1299,
    oldPrice: 1899,
    image: '/images/red-dragon.jpg',
    images: ['/images/red-dragon.jpg'],
    category: 'Монстры',
    categorySlug: 'monsters',
    subcategory: 'Драконы',
    description: 'Гигантский дракон для D&D, высота в масштабе 28 мм – 25 см. Крылья съёмные для печати.',
    shortDesc: 'Повелитель небес',
    fileFormat: 'STL, LYS',
    scale: '28mm',
    type: 'monster',
    faction: 'Драконы',
    gameSystem: 'Dungeons & Dragons',
    tags: ['дракон', 'фэнтези', 'монстр'],
    inStock: true,
    downloadsCount: 560,
    isDigital: true,
    popularity: 92,
    dateAdded: '2025-01-20',
    featured: true,
    new: false,
  },
  {
    id: '5',
    name: 'Техножрец Доминус',
    slug: 'techpriest-dominus',
    price: 449,
    image: '/images/techpriest.jpg',
    images: ['/images/techpriest.jpg'],
    category: 'Космодесант',
    categorySlug: 'space-marines',
    subcategory: 'Герои',
    description: 'Мастер сервиторов и благословенных машин. Сложная детализация для Adeptus Mechanicus.',
    shortDesc: 'Служитель Омниссии',
    fileFormat: 'STL',
    scale: '32mm',
    type: 'hero',
    faction: 'Адептус Механикус',
    gameSystem: 'Warhammer 40k',
    tags: ['техножрец', 'империум', 'герой'],
    inStock: true,
    downloadsCount: 940,
    isDigital: true,
    popularity: 88,
    dateAdded: '2025-02-10',
    featured: false,
    new: false,
  },
  {
    id: '6',
    name: 'Траншейная пушка «Гром»',
    slug: 'thunder-trench-gun',
    price: 699,
    image: '/images/trench-gun.jpg',
    images: ['/images/trench-gun.jpg'],
    category: 'Trench Crusade',
    categorySlug: 'trench-crusade',
    subcategory: 'Артиллерия',
    description: 'Тяжёлое орудие для обороны траншей. Печатается без поддержек.',
    shortDesc: 'Артиллерия',
    fileFormat: 'STL, OBJ',
    scale: '28mm',
    type: 'vehicle',
    faction: 'Антанта',
    gameSystem: 'Trench Crusade',
    tags: ['пушка', 'артиллерия', 'техника'],
    inStock: true,
    downloadsCount: 340,
    isDigital: true,
    popularity: 74,
    dateAdded: '2025-02-15',
    featured: false,
    new: true,
  },
  {
    id: '7',
    name: 'Лич-некромант',
    slug: 'lich-necromancer',
    price: 399,
    image: '/images/lich.jpg',
    images: ['/images/lich.jpg'],
    category: 'Фэнтези герои',
    categorySlug: 'fantasy-heroes',
    subcategory: 'Маги',
    description: 'Могущественный лич с книгой заклинаний. Подходит для D&D и Pathfinder.',
    shortDesc: 'Повелитель мёртвых',
    fileFormat: 'STL',
    scale: '28mm',
    type: 'hero',
    faction: 'Нежить',
    gameSystem: 'Dungeons & Dragons',
    tags: ['нежить', 'маг', 'герой'],
    inStock: true,
    downloadsCount: 720,
    isDigital: true,
    popularity: 82,
    dateAdded: '2025-02-20',
    featured: false,
    new: false,
  },
  {
    id: '8',
    name: 'Хаосный лорд на драконе',
    slug: 'chaos-lord-dragon',
    price: 1599,
    oldPrice: 1999,
    image: '/images/chaos-dragon.jpg',
    images: ['/images/chaos-dragon.jpg'],
    category: 'Легионы Хаоса',
    categorySlug: 'chaos',
    subcategory: 'Монстры',
    description: 'Эпическая модель для Warhammer Fantasy или Age of Sigmar.',
    shortDesc: 'Владыка Хаоса',
    fileFormat: 'STL, ZIP',
    scale: '32mm',
    type: 'monster',
    faction: 'Воин Хаоса',
    gameSystem: 'Warhammer Fantasy',
    tags: ['хаос', 'дракон', 'монстр'],
    inStock: true,
    downloadsCount: 450,
    isDigital: true,
    popularity: 90,
    dateAdded: '2025-01-25',
    featured: true,
    new: false,
  },
  {
    id: '9',
    name: 'Траншейный медик «Эскулап»',
    slug: 'trench-medic',
    price: 299,
    image: '/images/trench-medic.jpg',
    images: ['/images/trench-medic.jpg'],
    category: 'Trench Crusade',
    categorySlug: 'trench-crusade',
    subcategory: 'Поддержка',
    description: 'Полевой медик с сумкой и инструментами. Спасает раненых в траншеях.',
    shortDesc: 'Лекарь войны',
    fileFormat: 'STL',
    scale: '32mm',
    type: 'infantry',
    faction: 'Антанта',
    gameSystem: 'Trench Crusade',
    tags: ['медик', 'поддержка', 'пехота'],
    inStock: true,
    downloadsCount: 450,
    isDigital: true,
    popularity: 70,
    dateAdded: '2025-03-01',
    featured: false,
    new: true,
  },
  {
    id: '10',
    name: 'Пулемётный расчёт «Град»',
    slug: 'machine-gun-crew',
    price: 549,
    image: '/images/machine-gun.jpg',
    images: ['/images/machine-gun.jpg'],
    category: 'Trench Crusade',
    categorySlug: 'trench-crusade',
    subcategory: 'Тяжёлая пехота',
    description: 'Два бойца с тяжёлым пулемётом. Для обороны позиций.',
    shortDesc: 'Огневая мощь',
    fileFormat: 'STL, OBJ',
    scale: '32mm',
    type: 'infantry',
    faction: 'Антанта',
    gameSystem: 'Trench Crusade',
    tags: ['пулемёт', 'тяжёлое оружие', 'отряд'],
    inStock: true,
    downloadsCount: 310,
    isDigital: true,
    popularity: 76,
    dateAdded: '2025-03-05',
    featured: false,
    new: true,
  },
  {
    id: '11',
    name: 'Офицер-телефонист',
    slug: 'officer-telephonist',
    price: 399,
    image: '/images/officer.jpg',
    images: ['/images/officer.jpg'],
    category: 'Trench Crusade',
    categorySlug: 'trench-crusade',
    subcategory: 'Командиры',
    description: 'Командир с полевым телефоном. Позволяет призывать артиллерию.',
    shortDesc: 'Командир взвода',
    fileFormat: 'STL',
    scale: '32mm',
    type: 'hero',
    faction: 'Антанта',
    gameSystem: 'Trench Crusade',
    tags: ['офицер', 'командир', 'герой'],
    inStock: true,
    downloadsCount: 280,
    isDigital: true,
    popularity: 68,
    dateAdded: '2025-03-10',
    featured: false,
    new: true,
  },
  {
    id: '12',
    name: 'Траншейный снайпер «Кукушка»',
    slug: 'trench-sniper',
    price: 349,
    image: '/images/sniper.jpg',
    images: ['/images/sniper.jpg'],
    category: 'Trench Crusade',
    categorySlug: 'trench-crusade',
    subcategory: 'Элита',
    description: 'Снайпер в маскировочном плаще с винтовкой. Для скрытной войны.',
    shortDesc: 'Меткий стрелок',
    fileFormat: 'STL, OBJ',
    scale: '32mm',
    type: 'infantry',
    faction: 'Антанта',
    gameSystem: 'Trench Crusade',
    tags: ['снайпер', 'скрытность', 'элита'],
    inStock: true,
    downloadsCount: 520,
    isDigital: true,
    popularity: 84,
    dateAdded: '2025-03-12',
    featured: false,
    new: true,
  },
  {
    id: '13',
    name: 'Орк-мародёр с чоппой',
    slug: 'ork-marauder',
    price: 299,
    image: '/images/ork.jpg',
    images: ['/images/ork.jpg'],
    category: 'Орки',
    categorySlug: 'orks',
    subcategory: 'Пехота',
    description: 'Здоровенный орк с огромной чоппой. Для Warhammer 40k и фэнтези.',
    shortDesc: 'Зелёная волна',
    fileFormat: 'STL',
    scale: '32mm',
    type: 'infantry',
    faction: 'Орки',
    gameSystem: 'Warhammer 40k',
    tags: ['орк', 'пехота', 'ближний бой'],
    inStock: true,
    downloadsCount: 680,
    isDigital: true,
    popularity: 77,
    dateAdded: '2025-02-05',
    featured: false,
    new: false,
  },
  {
    id: '14',
    name: 'Эльфийский лучник',
    slug: 'elf-archer',
    price: 249,
    image: '/images/elf.jpg',
    images: ['/images/elf.jpg'],
    category: 'Эльфы',
    categorySlug: 'elves',
    subcategory: 'Стрелки',
    description: 'Изящный эльфийский лучник для D&D и Warhammer Fantasy.',
    shortDesc: 'Меткий стрелок',
    fileFormat: 'STL, OBJ',
    scale: '28mm',
    type: 'infantry',
    faction: 'Эльфы',
    gameSystem: 'Dungeons & Dragons',
    tags: ['эльф', 'лучник', 'фэнтези'],
    inStock: true,
    downloadsCount: 510,
    isDigital: true,
    popularity: 72,
    dateAdded: '2025-02-12',
    featured: false,
    new: false,
  },
  {
    id: '15',
    name: 'Некромант на троне',
    slug: 'necromancer-throne',
    price: 899,
    oldPrice: 1099,
    image: '/images/necromancer.jpg',
    images: ['/images/necromancer.jpg'],
    category: 'Фэнтези герои',
    categorySlug: 'fantasy-heroes',
    subcategory: 'Маги',
    description: 'Могучий некромант, восседающий на троне из костей. Центральная модель для армии нежити.',
    shortDesc: 'Властелин смерти',
    fileFormat: 'STL, ZIP',
    scale: '28mm',
    type: 'hero',
    faction: 'Нежить',
    gameSystem: 'Dungeons & Dragons',
    tags: ['некромант', 'нежить', 'герой'],
    inStock: true,
    downloadsCount: 390,
    isDigital: true,
    popularity: 86,
    dateAdded: '2025-01-30',
    featured: true,
    new: false,
  },
  {
    id: '16',
    name: 'Танк Leman Russ',
    slug: 'leman-russ-tank',
    price: 1299,
    image: '/images/tank.jpg',
    images: ['/images/tank.jpg'],
    category: 'Космодесант',
    categorySlug: 'space-marines',
    subcategory: 'Техника',
    description: 'Основной боевой танк Империума. Полностью детализированная модель.',
    shortDesc: 'Стальной кулак',
    fileFormat: 'STL, OBJ',
    scale: '28mm',
    type: 'vehicle',
    faction: 'Имперская Гвардия',
    gameSystem: 'Warhammer 40k',
    tags: ['танк', 'техника', 'империум'],
    inStock: true,
    downloadsCount: 610,
    isDigital: true,
    popularity: 89,
    dateAdded: '2025-02-18',
    featured: false,
    new: false,
  },
  {
    id: '17',
    name: 'Демонетта Слаанеш',
    slug: 'daemonette',
    price: 399,
    image: '/images/daemonette.jpg',
    images: ['/images/daemonette.jpg'],
    category: 'Легионы Хаоса',
    categorySlug: 'chaos',
    subcategory: 'Демоны',
    description: 'Изящный и смертоносный демон Слаанеш. Идеально для варгеймов.',
    shortDesc: 'Соблазнительница',
    fileFormat: 'STL',
    scale: '28mm',
    type: 'infantry',
    faction: 'Легионы Хаоса',
    gameSystem: 'Warhammer 40k',
    tags: ['демон', 'слаанеш', 'хаос'],
    inStock: true,
    downloadsCount: 470,
    isDigital: true,
    popularity: 73,
    dateAdded: '2025-03-08',
    featured: false,
    new: true,
  },
  {
    id: '18',
    name: 'Паладин Серебряного храма',
    slug: 'silver-temple-paladin',
    price: 449,
    image: '/images/paladin.jpg',
    images: ['/images/paladin.jpg'],
    category: 'Фэнтези герои',
    categorySlug: 'fantasy-heroes',
    subcategory: 'Воины',
    description: 'Закованный в латы паладин с двуручным мечом. Для D&D.',
    shortDesc: 'Защитник веры',
    fileFormat: 'STL',
    scale: '32mm',
    type: 'hero',
    faction: 'Орден Света',
    gameSystem: 'Dungeons & Dragons',
    tags: ['паладин', 'герой', 'рыцарь'],
    inStock: true,
    downloadsCount: 540,
    isDigital: true,
    popularity: 79,
    dateAdded: '2025-02-25',
    featured: false,
    new: false,
  },
  {
    id: '19',
    name: 'Варлок-инженер',
    slug: 'warlock-engineer',
    price: 379,
    image: '/images/warlock.jpg',
    images: ['/images/warlock.jpg'],
    category: 'Trench Crusade',
    categorySlug: 'trench-crusade',
    subcategory: 'Герои',
    description: 'Безумный инженер с экспериментальным оружием. Уникальный персонаж.',
    shortDesc: 'Гений разрушения',
    fileFormat: 'STL, OBJ',
    scale: '32mm',
    type: 'hero',
    faction: 'Содружество',
    gameSystem: 'Trench Crusade',
    tags: ['инженер', 'техномагия', 'герой'],
    inStock: true,
    downloadsCount: 300,
    isDigital: true,
    popularity: 65,
    dateAdded: '2025-03-15',
    featured: false,
    new: true,
  },
  {
    id: '20',
    name: 'Пехотный взвод «Стальные каски»',
    slug: 'steel-helmets-squad',
    price: 599,
    image: '/images/squad.jpg',
    images: ['/images/squad.jpg'],
    category: 'Trench Crusade',
    categorySlug: 'trench-crusade',
    subcategory: 'Отряды',
    description: 'Набор из 10 солдат с винтовками. Для создания армии.',
    shortDesc: 'Костяк армии',
    fileFormat: 'STL, ZIP',
    scale: '32mm',
    type: 'infantry',
    faction: 'Антанта',
    gameSystem: 'Trench Crusade',
    tags: ['пехота', 'отряд', 'траншея'],
    inStock: true,
    downloadsCount: 680,
    isDigital: true,
    popularity: 91,
    dateAdded: '2025-03-18',
    featured: true,
    new: true,
  },
]

export const categories: Category[] = [
  { 
    name: 'D&D', 
    slug: 'space-marines', 
    image: '/images/universe_images/dnd.jpg' 
  },
  { 
    name: 'Trench Crusade', 
    slug: 'trench-crusade', 
    image: '/images/universe_images/trench-crusade.jpg' 
  },
]